# 基本设置
title: Your Name
email: your-email@example.com
description: >- 
  Your personal website description
baseurl: "" # 对于username.github.io仓库，这里应该为空
url: "https://doloming.github.io" # 替换为您的GitHub Pages URL

# 构建设置
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

# 主题设置
minimal_mistakes_skin: "air"

# 站点作者
author:
  name: "Your Name"
  bio: "Your bio"
  location: "Your Location"

# 默认布局设置
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 包含的文件/文件夹
include:
  - _pages
  - assets

# 排除的文件/文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
